#!/usr/bin/ruby

require "open3"
cmd = "raco scv-gt -b"
main = ARGV[2]
files = Dir.glob(File.dirname(main) + "/**/*.rkt")
full = ([cmd] + files).join(" ")

# capture output
output, error, _ = Open3.capture3(full)

f = __dir__ + "/../blames.dat"
results = Marshal.load(File.read(f))
results << output
File.open(f, "w") do |handle|
  handle.write(Marshal.dump(results))
end

raise error unless error == ""
